
import mongoose from 'mongoose';
import Product from './models/Product.js';
import CartItem from './models/CartItem.js'; 
import connectDB from './config/db.js';
import 'dotenv/config'; 

connectDB();

const mockProducts = [
    { 
        name: 'Vintage Vinyl Record', 
        price: 29.99, 
        description: '100% authentic vintage record.', 
        imageUrl: 'https://picsum.photos/id/15/300/200' 
    },
    { 
        name: 'A.I. Generated Art Print', 
        price: 89.99, 
        description: 'Unique piece generated by a cutting-edge algorithm.', 
        imageUrl: 'https://picsum.photos/id/117/300/200' 
    },
    { 
        name: 'roadmap', 
        price: 39.50, 
        description: 'Detailed roadmap .', 
        imageUrl: 'https://picsum.photos/id/191/300/200' 
    },
    { 
        name: 'camera kit', 
        price: 199.00, 
        description: 'Complete camera kit.', 
        imageUrl: 'https://picsum.photos/id/250/300/200'
    },
    { 
        name: 'string kit', 
        price: 45.00, 
        description: 'Complete string kit.', 
        imageUrl: 'https://picsum.photos/id/145/300/200' 
    },
    { 
        name: 'assessory kit', 
        price: 24.99, 
        description: 'Complete accessory kit.', 
        imageUrl: 'https://picsum.photos/id/26/300/200' 
    },
];

const seedDB = async () => {
    try {
        await Product.deleteMany({});
        await CartItem.deleteMany({});
        
        await Product.insertMany(mockProducts);
        
        console.log('Database fully cleared and seeded with final themed data.');
        mongoose.connection.close();
    } catch (err) {
        console.error('Error seeding database:', err);
        mongoose.connection.close();
    }
};

seedDB();